# Generated by Django 4.1.7 on 2023-03-30 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_rename_contacts_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='disabled',
            field=models.BooleanField(default=False),
        ),
    ]
