# Generated by Django 4.1.7 on 2023-04-06 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0003_contact_disabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='photo',
            field=models.ImageField(blank=True, upload_to='photos/%Y/%m/'),
        ),
    ]
