# Generated by Django 4.1.7 on 2023-04-21 21:11

import contacts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0004_contact_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='photo',
            field=models.ImageField(blank=True, upload_to=contacts.models.upload_to),
        ),
    ]
